//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Компьютер
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Компьютер()
        {
            this.Накладная = new HashSet<Накладная>();
        }
    
        public int Код_компьютера { get; set; }
        public string Процессор { get; set; }
        public string Видеокарта { get; set; }
        public string Мат_плата { get; set; }
        public string Объём_ОЗУ { get; set; }
        public string Жёсткий_диск { get; set; }
        public Nullable<int> Местоположение { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Накладная> Накладная { get; set; }
    }
}
