//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Накладная
    {
        public int Код_накладной { get; set; }
        public Nullable<int> Компьютер { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> От_куда { get; set; }
        public Nullable<int> Куда { get; set; }
        public Nullable<int> Ответственный { get; set; }
    
        public virtual Компьютер Компьютер1 { get; set; }
        public virtual Местоположения Местоположения { get; set; }
        public virtual Местоположения Местоположения1 { get; set; }
        public virtual Работник_тех_отдела Работник_тех_отдела { get; set; }
    }
}
